### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by 9d9ae2** [Its-Vichy/XProxy#13]
I downloaded the source code of the program on Arch Linux AMD64 and tried to build the program (`cd /path/to/src && go build`), but the build fails with the error:
``` user@archpc:~/Desktop/XProxy-master $ go build
# Proxy/components/utils
components/utils/console.go:56:26: undefined: syscall.LoadLibrary
components/utils/console.go:61:17: undefined: syscall.FreeLibrary
components/utils/console.go:63:24: undefined: syscall.GetProcAddress
components/utils/console.go:68:59: undefined: syscall.StringToUTF16Ptr ```
What can I do?

**Comment by Its-Vichy** [comment]
**On Linux, syscall library can't be use**d, you need to remove it and replace the title function with somes printf escape code.
If you can't code, just delete everythind who is related to console title on main.go and console.go.
