### ISSUE TITLE
Custom website check

### ISSUE THREAD

**Issue by Beykir** [Its-Vichy/XProxy#16]
Hello,

can you please add the function, to test the proxys against a custom website with a custom keyword in response text?

for example check proxys against https://google.com and if the keyword <title>Google</title> in response text proxy is valid

thank you

**Comment by Its-Vichy** [comment]
For sure.

**Comment by Its-Vichy** [comment]
Thanks for the idea. ( https://github.com/Its-Vichy/XProxy/commit/f34734880e5b4c92ab8e8f8d5d344287f1ecd6a7 )
