### ISSUE TITLE
[todo] save proxies into multiple files

### ISSUE THREAD

**Issue by HyperBeats** [Its-Vichy/XProxy#5]
possible d'ajouté le faite que les proxy se save dans plusieur fichier test exemple http.txt, socks4.txt, socks5.txt

**Comment by Its-Vichy** [comment]
Ouais je vais m'en occuper

**Comment by HyperBeats** [comment]
nickel

**Comment by Its-Vichy** [comment]
Done

https://github.com/Its-Vichy/XProxy/commit/0a53aad8f693637250aa4358c28eaee41adf113a
